### ISSUE TITLE
Add a way for users to view the collected data ingame

### ISSUE THREAD

**Issue by SanderKnauff** [Sansko1337/ShinyLogger#2]
_Requested by: TacticalTickler (JP)#1337_
**Curent Situation**
The only way to view the data is by server administrators who have access to the files. While this is okay for big investegative situations, it's not a proactive solution to the problem of people cheating to collect shinies. 

**Desired Situation**
Hunting cheaters and keeping order on servers is usually the job of moderators. It's preferable if they have access to the data as well.
Create a user interface to display the current list of players who have caught shinies.
This could either be a chat message or a GUI.
Also add a permission node for the command so server owners can delegate the permissions to their moderators.

**Comment by Sansko1337** [comment]
Implemented in Release 1.1.0
